// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ79CKf2LqYSGbJxRgPg_79AfVZqGM5rI',
    appId: '1:447844619461:web:a3813fafefdd7be3b58cac',
    messagingSenderId: '447844619461',
    projectId: 'praktikummobile-4e7de',
    authDomain: 'praktikummobile-4e7de.firebaseapp.com',
    storageBucket: 'praktikummobile-4e7de.appspot.com',
    measurementId: 'G-G7V1FPLQM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe_GL_IWa_1McdqTPHszYGxca97A9efII',
    appId: '1:447844619461:android:2bd228b7bd3e7336b58cac',
    messagingSenderId: '447844619461',
    projectId: 'praktikummobile-4e7de',
    storageBucket: 'praktikummobile-4e7de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmBMmuFD6e2TY-SGYSNIm7eSvK1zfCNKE',
    appId: '1:447844619461:ios:54eee10686375793b58cac',
    messagingSenderId: '447844619461',
    projectId: 'praktikummobile-4e7de',
    storageBucket: 'praktikummobile-4e7de.appspot.com',
    iosBundleId: 'com.example.skibidiskibidisigma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmBMmuFD6e2TY-SGYSNIm7eSvK1zfCNKE',
    appId: '1:447844619461:ios:54eee10686375793b58cac',
    messagingSenderId: '447844619461',
    projectId: 'praktikummobile-4e7de',
    storageBucket: 'praktikummobile-4e7de.appspot.com',
    iosBundleId: 'com.example.skibidiskibidisigma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ79CKf2LqYSGbJxRgPg_79AfVZqGM5rI',
    appId: '1:447844619461:web:8cc5df4381595ca6b58cac',
    messagingSenderId: '447844619461',
    projectId: 'praktikummobile-4e7de',
    authDomain: 'praktikummobile-4e7de.firebaseapp.com',
    storageBucket: 'praktikummobile-4e7de.appspot.com',
    measurementId: 'G-HSF5T8DE5L',
  );

}